modLoader="neoforge"
loaderVersion="${loader_version_range}" # e.g. [4,)

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

# Optional metadata (customize if needed)
# logoFile="logo.png"
# credits="Thanks to ElocinDev for the original Forge version"
# displayURL="https://example.com"
# issueTrackerURL="https://github.com/yourrepo/issues"

[[mixins]]
config="mixins.${mod_id}.json"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
